name: calibre-web

on:
  push:
    paths:
    - 'calibre-web/Dockerfile'
    - 'calibre-web/root/**'
  workflow_dispatch:

jobs:
  job1:
    name: buildx tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Set env'
        run: |
          echo "CALIBRE_WEB_VER=$(echo `grep -n "CALIBRE_WEB_VER=" calibre-web/Dockerfile`|awk -F: '{print $2}'|cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "CALIBRE_VER=$(echo `grep -n "CALIBRE_VER=" calibre-web/Dockerfile`|awk -F: '{print $2}'|cut -d "=" -f 2)" >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./calibre-web
          file: ./calibre-web/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            johngong/calibre-web:latest
            johngong/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}
            ghcr.io/gshang2017/calibre-web:latest
            ghcr.io/gshang2017/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/calibre-web
          short-description: calibre-web:${{ env.CALIBRE_WEB_VER }}电子书管理带ebook-convert转换。
          readme-filepath: ./calibre-web/README.md
