name: nginx-fancyindex

on:
  push:
    paths:
    - 'nginx-fancyindex/Dockerfile'
    - 'nginx-fancyindex/file.conf'
    - 'nginx-fancyindex/.theme/**'
  workflow_dispatch:

jobs:
  job1:
    name: buildx tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Set env'
        run: |
          echo "BUILD_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "NGINX_VER=$(echo `grep -n "FROM alpine:" nginx-fancyindex/Dockerfile`|awk -F: '{print $2}'|tr -d ' ')" >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./nginx-fancyindex
          file: ./nginx-fancyindex/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            nobody114/nginx-fancyindex:latest
            nobody114/nginx-fancyindex:${{ env.BUILD_DATE }}