name: tt-rss

on:
  push:
    paths:
    - 'tt-rss-plugins/Dockerfile'
    - 'tt-rss-plugins/root/**'
  workflow_dispatch:

jobs:
  job1:
    name:  buildx tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Set env'
        run: |
          echo "TTRSS_VER=$(echo `grep -n "TTRSS_VER=" tt-rss-plugins/Dockerfile`|awk -F= '{print $2}')" >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./tt-rss-plugins
          file: ./tt-rss-plugins/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            johngong/tt-rss:latest
            johngong/tt-rss:plugins-${{ env.TTRSS_VER }}
            ghcr.io/gshang2017/tt-rss:latest
            ghcr.io/gshang2017/tt-rss:plugins-${{ env.TTRSS_VER }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/tt-rss
          short-description: Tiny Tiny RSS:plugins-${{ env.TTRSS_VER }},集成postgres数据库,mercury-parser-api及一些常用插件
          readme-filepath: ./tt-rss-plugins/README.md
